apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-appv4
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ismail17/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
